### ISSUE TITLE
take photo from camera

### ISSUE THREAD

**Issue by MichaelSamir47** [qchenqizhi/QCropper#14]
how can get photo from camera and passing to cropViewController?

**Comment by haib3rl** [comment]
if you want to implement a Camera inside your App:
 Have a look at https://medium.com/@barbulescualex/making-a-custom-camera-in-ios-ea44e3087563

Use this function to convert the CIImage to an UIImage  otherwise the function "originalImage.cropped(withCropperState: state)" will always return the OriginalImage
```
func convert(cmage:CIImage) -> UIImage
    {
        let context:CIContext = CIContext.init(options: nil)
        let cgImage:CGImage = context.createCGImage(cmage, from: cmage.extent)!
        let image:UIImage = UIImage.init(cgImage: cgImage)
        return image
    }
```
For the Cropper have a look at https://github.com/qchenqizhi/QCropper/blob/master/Example/ViewController.swift
Just use this from the Camera for example via a button. Instead of  the "imagePickerController" function

```
let cropper = CropperViewController(originalImage: image)
cropper.delegate = self
self.present(cropper, animated: true, completion: nil)
```
